spring-cloud-contributors:
  - adriancole
  - dsyer
  - marcingrzejszczak
  - OlgaMaciaszek
  - ryanjbaxter
  - spencergibb

issuebot:
  monitoring:
    repositories:
      - organization: spring-cloud
        name: spring-cloud-aws
        collaborators: ${spring-cloud-contributors}
      - organization: spring-cloud
        name: spring-cloud-build
        collaborators: ${spring-cloud-contributors}
      - organization: spring-cloud
        name: spring-cloud-bus
        collaborators: ${spring-cloud-contributors}
      - organization: spring-cloud
        name: spring-cloud-cloudfoundry
        collaborators: ${spring-cloud-contributors}
      - organization: spring-cloud
        name: spring-cloud-commons
        collaborators: ${spring-cloud-contributors}
      - organization: spring-cloud
        name: spring-cloud-config
        collaborators: ${spring-cloud-contributors}
      - organization: spring-cloud
        name: spring-cloud-consul
        collaborators: ${spring-cloud-contributors}
      - organization: spring-cloud
        name: spring-cloud-contract
        collaborators: ${spring-cloud-contributors}
      - organization: spring-cloud
        name: spring-cloud-gateway
        collaborators: ${spring-cloud-contributors}
      - organization: spring-cloud
        name: spring-cloud-kubernetes
        collaborators: ${spring-cloud-contributors}
      - organization: spring-cloud
        name: spring-cloud-netflix
        collaborators: ${spring-cloud-contributors}
      - organization: spring-cloud
        name: spring-cloud-openfeign
        collaborators: ${spring-cloud-contributors}
      - organization: spring-cloud
        name: spring-cloud-security
        collaborators: ${spring-cloud-contributors}
      - organization: spring-cloud
        name: spring-cloud-sleuth
        collaborators: ${spring-cloud-contributors}
      - organization: spring-cloud
        name: spring-cloud-zookeeper
        collaborators: ${spring-cloud-contributors}
      - organization: spring-cloud
        name: spring-cloud-circuitbreaker
        collaborators: ${spring-cloud-contributors}
  triage:
    label: "waiting-for-triage"
  feedback:
    required_label: "waiting for feedback"
    provided_label: "feedback-provided"
    reminder_label: "feedback-reminder"
    reminder_comment: >
      If you would like us to look at this issue, please provide the requested
      information. If the information is not provided within the next 7 days this issue
      will be closed.
    close_comment: >
      Closing due to lack of requested feedback. If you would like us to look at this
      issue, please provide the requested information and we will re-open the issue.
  question:
    label: "question"
    close_comment: >
      Closing due to age of the question. If you would like us to look at this
      issue, please comment and we will look at re-opening the issue.
